### ISSUE TITLE
Consider speeding up state machine

### ISSUE THREAD

**Issue by jcjones** [mozilla/authenticator-rs#95]
From https://github.com/webcompat/web-bugs/issues/30336, it sounds like perhaps the waits at https://github.com/mozilla/authenticator-rs/blob/9818cb7d997b53ebdc25f40b3c313a6246d99d94/src/statemachine.rs#L111 and https://github.com/mozilla/authenticator-rs/blob/9818cb7d997b53ebdc25f40b3c313a6246d99d94/src/statemachine.rs#L199 are too long.

I should configure my tokens to use the first slot for TOTP and attempt to recreate the upstream issue, lower the timeouts and see if I can improve it.

**Comment by baloo** [comment]
my understanding is that those sleeps are required when a token replies with `SW_CONDITIONS_NOT_SATISFIED (The request was rejected due to test-of-user-presence being required.)` (https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-raw-message-formats-v1.2-ps-20170411.html#status-codes).

Whenever an authenticate command is sent, the token will reject the command with this error until the user presses the button, the browser has to keep retrying the same command every now and then, until it returns a non-error status (or a 30sec total timeout elapsed). 100ms to retry does not look unreasonable to me.

(On that subject, I believe the design in fido2 is better on that point, and the token just reply with a keepalive, browser has to keep polling those until command completion.)

In the original issue, @MarkBennett says that it works if the yubikey is inserted before, but not after call to `navigator.credentials`. I would tend to think the issue is with https://github.com/mozilla/authenticator-rs/blob/674fd0b46bd1659973bbf8db5e7a4e819a38b9cb/src/macos/monitor.rs#L34 instead which is in charge of detecting new devices (via iokit), and starts a dedicated runloop/thread to handle devices.

I might be missing something here though.
